name: caloriscan
description: A Flutter app for scanning meals, estimating calories and macronutrients, and tracking meal history.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.0
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true